name: Build Binaries for Release

on:
  release:
    types: [published]

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build release binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64 
            goos: linux
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build Go binaries
        id: buildgo
        uses: wangyoucao577/go-release-action@v1
        with:
          upload: true
          overwrite: true
          compress_assets: "OFF" 
          pre_command: "export CGO_ENABLED=0"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "1.24"
          binary_name: "jsonvalidate"
          project_path: .
          release_tag: ${{ github.event.release.tag_name }}
          release_name: ${{ github.event.release.tag_name }}
          ldflags: -s -X main.version=${{ github.event.release.tag_name }}
      - name: Show release asset directory
        run: ls -alR ${{ steps.buildgo.outputs.release_asset_dir }}
      - name: 'Upload GitHub Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: jsonvalidate-${{ github.event.release.tag_name }}-linux-amd64
          path: ${{ steps.buildgo.outputs.release_asset_dir }}/
          overwrite: true
  debian:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: jsonvalidate-${{ github.event.release.tag_name }}-linux-amd64 
          path: dist/
      - name: workdir
        run:  pwd && ls -al dist/
      - name: Install dpkg tools
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev
      - name: Create Debian package
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          mkdir -p jsonvalidate_${VERSION}_amd64/usr/local/bin
          cp dist/jsonvalidate-v${VERSION}-linux-amd64 jsonvalidate_${VERSION}_amd64/usr/local/bin/jsonvalidate
          chmod 755 jsonvalidate_${VERSION}_amd64/usr/local/bin/jsonvalidate
          mkdir -p jsonvalidate_${VERSION}_amd64/DEBIAN
          cat <<EOF > jsonvalidate_${VERSION}_amd64/DEBIAN/control
          Package: jsonvalidate
          Version: ${VERSION}
          Section: utils
          Priority: optional
          Architecture: amd64
          Maintainer: vicendominguez [https://github.com/vicendominguez]
          Description: just a ultrafast json validator
          EOF
          dpkg-deb --build jsonvalidate_${VERSION}_amd64
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: jsonvalidate_**.deb
